name: Automatically merge pull requests on certain labels
on:
  pull_request:
    types:
      - labeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_run:
    types:
      - completed
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: "pascalgn/automerge-action@v0.4.2"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "mergeready,!donotmerge,!after next release"
          MERGE_METHOD: "squash"
          UPDATE_LABELS: "mergeready"
          UPDATE_METHOD: "merge"
